const css = `
  :host{display:block;color:var(--primary-text-color);background:var(--primary-background-color);min-height:100%}
  *{box-sizing:border-box} header{display:flex;gap:12px;align-items:center;padding:16px 20px;border-bottom:1px solid var(--divider-color)}
  header h1{font-size:22px;margin:0 auto 0 0}.tabs{display:flex;gap:8px}.tabs button.active{background:var(--primary-color);color:var(--text-primary-color)}
  button,select,input,textarea{font:inherit}button{border:0;border-radius:8px;padding:9px 13px;cursor:pointer;background:var(--secondary-background-color);color:inherit}
  button.primary{background:var(--primary-color);color:var(--text-primary-color)}main{padding:18px;max-width:1500px;margin:auto}.toolbar{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-bottom:14px}
  .grid{display:grid;grid-template-columns:minmax(360px,1fr) minmax(320px,1fr);gap:18px}.card{background:var(--card-background-color);border-radius:12px;padding:16px;box-shadow:var(--ha-card-box-shadow)}
  textarea{width:100%;min-height:62vh;border:1px solid var(--divider-color);border-radius:8px;padding:12px;background:var(--code-editor-background-color,#111);color:var(--primary-text-color);font-family:monospace;line-height:1.4;tab-size:2}
  label{display:grid;gap:5px;margin:10px 0}input,select{padding:9px;border:1px solid var(--divider-color);border-radius:7px;background:var(--card-background-color);color:inherit}.error{color:var(--error-color)}.ok{color:var(--success-color)}
  .preview-wrap{height:68vh;display:flex;align-items:center;justify-content:center;overflow:hidden;background:repeating-conic-gradient(#7771 0 25%,transparent 0 50%) 50%/18px 18px}
  .device{background:#121212;color:#fff;border:8px solid #292929;border-radius:18px;overflow:hidden;transform-origin:center;display:flex;flex-direction:column}.device-tabs{display:flex;gap:4px;padding:6px;background:#222}.device-tabs span{flex:1;text-align:center;padding:5px;background:#333;border-radius:4px}.dash{display:grid;gap:8px;padding:8px;overflow:hidden;flex:1}.widget{min-height:50px;border-radius:8px;background:#2d2d2d;padding:9px;overflow:hidden}.muted{opacity:.72;font-size:.9em}.device-list{display:grid;gap:8px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between;padding:10px;background:var(--secondary-background-color);border-radius:8px}
  .visual-tab{border:1px solid var(--divider-color);border-radius:8px;padding:10px;margin:8px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}.code{font-size:36px;letter-spacing:.16em;font-weight:700}.advanced{border-left:4px solid var(--warning-color);padding-left:10px}
  @media(max-width:850px){.grid,.pair{grid-template-columns:1fr}.preview-wrap{height:50vh}textarea{min-height:45vh}}
`;

class RustyHamaPanel extends HTMLElement {
  constructor(){super();this.attachShadow({mode:'open'});this.page='dashboard';this.mode='json';this.view='profile';this.orientation='current';this.model=null;this.profileId='default';this.deviceId='';this.text='';this.message='';}
  set hass(value){this._hass=value;if(!this.model)this.refresh();}
  get hass(){return this._hass;}
  async call(type,data={}){return this.hass.callWS({type:`rustyhama/${type}`,...data});}
  async refresh(){try{this.model=await this.call('get_snapshot');this.profileId=this.model.profiles[this.profileId]?this.profileId:Object.keys(this.model.profiles)[0];this.deviceId=this.deviceId||this.model.devices[0]?.device_id||'';this.syncText();this.render();}catch(e){this.message=String(e.message||e);this.render();}}
  selectedDevice(){return this.model?.devices.find(d=>d.device_id===this.deviceId);}
  profile(){return this.model?.profiles[this.profileId];}
  source(){const d=this.selectedDevice();if(this.view==='effective')return d?.effective_config||{};if(this.view==='override')return d?.override||{};return this.profile()?.draft||{};}
  syncText(){this.text=JSON.stringify(this.source(),null,2);}
  escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  parse(){try{const value=JSON.parse(this.text);this.message='JSON valid';return value;}catch(e){this.message=`JSON: ${e.message}`;return null;}}
  async save(){const config=this.parse();if(!config)return this.render();try{if(this.view==='override'){await this.call('update_device',{device_id:this.deviceId,override:config});}else if(this.view==='profile'){await this.call('save_profile',{profile_id:this.profileId,name:this.profile().name,config});}else{throw new Error('Effective configuration is read-only');}this.message='Draft saved';await this.refresh();}catch(e){this.message=String(e.message||e);this.render();}}
  async publish(){try{const result=await this.call('publish_profile',{profile_id:this.profileId});this.message=`Published revision ${result.revision}`;await this.refresh();}catch(e){this.message=String(e.message||e);this.render();}}
  updateVisual(path,value){const draft=structuredClone(this.profile().draft);if(path==='theme')draft.theme=value;this.model.profiles[this.profileId].draft=draft;this.text=JSON.stringify(draft,null,2);this.render();}
  addTab(){const draft=structuredClone(this.profile().draft);draft.tabs.push({id:`tab_${Date.now()}`,title:'New tab',columns:2,widgets:[]});this.model.profiles[this.profileId].draft=draft;this.text=JSON.stringify(draft,null,2);this.render();}
  addWidget(tabIndex){const draft=structuredClone(this.profile().draft);draft.tabs[tabIndex].widgets.push({id:`widget_${Date.now()}`,type:'entity',entity_id:'light.example'});this.model.profiles[this.profileId].draft=draft;this.text=JSON.stringify(draft,null,2);this.render();}
  setTabField(index,key,value){const draft=structuredClone(this.profile().draft);draft.tabs[index][key]=key==='columns'?Number(value):value;this.model.profiles[this.profileId].draft=draft;this.text=JSON.stringify(draft,null,2);this.render();}
  preview(){const d=this.selectedDevice();const config=(this.parse()||this.source());const display=d?.display||{};let width=Number(display.usable_width_px||display.activity_width_px||1280),height=Number(display.usable_height_px||display.activity_height_px||800);if(this.orientation!=='current'&&((this.orientation==='portrait')!==(height>=width)))[width,height]=[height,width];const density=Number(display.density||display.density_dpi/160||1);const font=Number(display.font_scale||1);const tabs=config.tabs||[];const first=tabs[0]||{columns:1,widgets:[]};const states=this.hass?.states||{};return `<div class="preview-wrap" id="preview"><div class="device" id="device" style="width:${width}px;height:${height}px;font-size:${14*density*font}px"><div class="device-tabs">${tabs.map(t=>`<span>${this.escape(t.title||t.id)}</span>`).join('')}</div><div class="dash" style="grid-template-columns:repeat(${Number(first.columns||2)},1fr)">${(first.widgets||[]).map(w=>{const id=w.entity_id||w.entity;const state=id&&states[id];return `<div class="widget" style="grid-column:span ${Number(w.colspan||1)}"><b>${this.escape(w.title||w.name||w.type)}</b><div>${this.escape(state?.state??id??'')}</div></div>`}).join('')}</div></div></div><p class="muted">${d?`${width} × ${height}px · ${display.density_dpi||'?'} dpi · font ${font}`:'Generic preview (not device-specific)'}</p>`;}
  fitPreview(){requestAnimationFrame(()=>{const wrap=this.shadowRoot.querySelector('#preview'),device=this.shadowRoot.querySelector('#device');if(!wrap||!device)return;const scale=Math.min((wrap.clientWidth-28)/device.offsetWidth,(wrap.clientHeight-28)/device.offsetHeight,1);device.style.transform=`scale(${scale})`;});}
  dashboard(){if(!this.model)return '<p>Loading…</p>';const profile=this.profile();return `<div class="toolbar"><select id="profile">${Object.entries(this.model.profiles).map(([id,p])=>`<option value="${this.escape(id)}" ${id===this.profileId?'selected':''}>${this.escape(p.name)}</option>`).join('')}</select><select id="device"><option value="">Generic tablet</option>${this.model.devices.map(d=>`<option value="${d.device_id}" ${d.device_id===this.deviceId?'selected':''}>${this.escape(d.name)}</option>`).join('')}</select><select id="view"><option value="profile">Profile draft</option><option value="override" ${this.view==='override'?'selected':''}>Device override</option><option value="effective" ${this.view==='effective'?'selected':''}>Effective config</option></select><button id="jsonMode" class="${this.mode==='json'?'active':''}">JSON</button><button id="visualMode" class="${this.mode==='visual'?'active':''}">Visual</button><button id="save" class="primary">Save draft</button><button id="publish">Publish</button><span class="${this.message.includes('valid')||this.message.includes('saved')||this.message.includes('Published')?'ok':'error'}">${this.escape(this.message)}</span></div><div class="grid"><section class="card">${this.mode==='json'?`<textarea id="editor" spellcheck="false" ${this.view==='effective'?'readonly':''}>${this.escape(this.text)}</textarea>`:this.visual(profile)}</section><section class="card"><div class="toolbar"><select id="orientation"><option value="current">Current orientation</option><option value="portrait" ${this.orientation==='portrait'?'selected':''}>Portrait</option><option value="landscape" ${this.orientation==='landscape'?'selected':''}>Landscape</option></select></div>${this.preview()}</section></div>`;}
  visual(profile){const c=profile?.draft||{};return `<label>Theme<select id="theme"><option ${c.theme==='dark'?'selected':''}>dark</option><option ${c.theme==='light'?'selected':''}>light</option></select></label><h3>Tabs</h3>${(c.tabs||[]).map((t,i)=>`<div class="visual-tab"><label>Title<input data-tab="${i}" data-key="title" value="${this.escape(t.title||'')}"></label><label>Columns<input type="number" min="1" max="12" data-tab="${i}" data-key="columns" value="${Number(t.columns||2)}"></label><div>${(t.widgets||[]).map(w=>`<span class="muted">${this.escape(w.type)} · ${this.escape(w.id)}</span><br>`).join('')}</div><button data-widget="${i}">Add standard widget</button></div>`).join('')}<button id="addTab">Add tab</button><p class="advanced">Unknown and advanced blocks are preserved unchanged.</p>`;}
  devices(){const rows=(this.model?.devices||[]).map(d=>`<div class="row"><div><b>${this.escape(d.name)}</b><div class="muted">${d.online?'online':'offline'} · rev ${d.acknowledged_revision}/${d.config_revision} · ${this.escape(d.area_id||'no area')}</div></div><button data-open="${d.device_id}">Configure</button></div>`).join('');return `<div class="pair"><section class="card"><h2>Pair device</h2><label>Name<input id="pairName" value="RustyHAMA"></label><label>Profile<select id="pairProfile">${Object.entries(this.model?.profiles||{}).map(([id,p])=>`<option value="${id}">${this.escape(p.name)}</option>`).join('')}</select></label><label>Area ID<input id="pairArea" placeholder="Optional HA area ID"></label><label>Certificate SHA-256 fingerprint<input id="pairFingerprint" placeholder="Recommended for self-signed certificates"></label><button id="pairCreate" class="primary">Create pairing</button><div id="pairResult"></div></section><section class="card"><h2>Devices</h2><div class="device-list">${rows||'<p>No paired devices.</p>'}</div></section></div>`;}
  providers(){return `<section class="card"><h2>Provider connections</h2><p>Keys are stored only in private Home Assistant storage and never returned to this panel or a device.</p><label>ID<input id="providerId"></label><label>Type<select id="providerType"><option>immich</option><option>music_assistant</option></select></label><label>URL<input id="providerUrl"></label><label>API key / token<input id="providerKey" type="password" autocomplete="new-password"></label><button id="providerSave" class="primary">Save provider</button><h3>Configured</h3>${Object.entries(this.model?.providers||{}).map(([id,p])=>`<div class="row"><b>${this.escape(id)}</b><span>${this.escape(p.type)} · ${this.escape(p.url)}</span></div>`).join('')}</section>`;}
  render(){this.shadowRoot.innerHTML=`<style>${css}</style><header><h1>RustyHAMA</h1><nav class="tabs"><button data-page="dashboard" class="${this.page==='dashboard'?'active':''}">Dashboard</button><button data-page="devices" class="${this.page==='devices'?'active':''}">Devices</button><button data-page="providers" class="${this.page==='providers'?'active':''}">Providers</button></nav></header><main>${this.page==='dashboard'?this.dashboard():this.page==='devices'?this.devices():this.providers()}</main>`;this.bind();this.fitPreview();}
  bind(){this.shadowRoot.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{this.page=b.dataset.page;this.render()});const q=s=>this.shadowRoot.querySelector(s);if(this.page==='dashboard'&&this.model){q('#editor')?.addEventListener('input',e=>{this.text=e.target.value;this.fitPreview()});q('#profile').onchange=e=>{this.profileId=e.target.value;this.view='profile';this.syncText();this.render()};q('#device').onchange=e=>{this.deviceId=e.target.value;if(this.view!=='profile')this.syncText();this.render()};q('#view').onchange=e=>{this.view=e.target.value;this.syncText();this.render()};q('#jsonMode').onclick=()=>{this.mode='json';this.render()};q('#visualMode').onclick=()=>{this.mode='visual';this.render()};q('#save').onclick=()=>this.save();q('#publish').onclick=()=>this.publish();q('#orientation').onchange=e=>{this.orientation=e.target.value;this.render()};q('#theme')?.addEventListener('change',e=>this.updateVisual('theme',e.target.value));q('#addTab')?.addEventListener('click',()=>this.addTab());this.shadowRoot.querySelectorAll('[data-tab]').forEach(e=>e.onchange=x=>this.setTabField(Number(e.dataset.tab),e.dataset.key,x.target.value));this.shadowRoot.querySelectorAll('[data-widget]').forEach(e=>e.onclick=()=>this.addWidget(Number(e.dataset.widget)));}if(this.page==='devices'){q('#pairCreate').onclick=async()=>{try{const r=await this.call('create_pairing',{name:q('#pairName').value,profile_id:q('#pairProfile').value,area_id:q('#pairArea').value||null,certificate_fingerprint:q('#pairFingerprint').value||''});const qr=JSON.stringify({url:location.origin,qr_token:r.qr_token,certificate_fingerprint:r.certificate_fingerprint});q('#pairResult').innerHTML=`<p class="code">${r.code}</p><ha-qr-code data="${this.escape(qr)}"></ha-qr-code><p>Valid for ${Math.round(r.expires_in/60)} minutes.</p>`;}catch(e){q('#pairResult').textContent=e.message}};this.shadowRoot.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{this.deviceId=b.dataset.open;this.view='effective';this.page='dashboard';this.syncText();this.render()});}if(this.page==='providers'){q('#providerSave').onclick=async()=>{const type=q('#providerType').value,key=q('#providerKey').value;await this.call('save_provider',{provider_id:q('#providerId').value,provider:{type,url:q('#providerUrl').value,[type==='immich'?'api_key':'token']:key}});await this.refresh()};}}
}
customElements.define('rustyhama-panel',RustyHamaPanel);
