const DOCS_ROOT='https://daniel.snii.de/RustyHAMA/';
const TYPES=['light','switch','button','label','select','cover','fan','climate','media_player','clock','assist_button','camera','picture','history_graph','custom:mini-graph-card','weather_chart','calendar','custom:auto-entities','grid','blank'];
const TYPE_ICONS={light:'\ue0f0',switch:'\ue8b8',button:'\ue8b8',label:'\ue892',select:'\ue5c5',cover:'\uec11',fan:'\uefd8',climate:'\uf076',media_player:'\ue405',clock:'\ue8b5',datetime:'\ue8b5',assist_button:'\ue029',camera:'\ue3af',picture:'\ue3f4',image:'\ue3f4',history_graph:'\ue6e1','custom:mini-graph-card':'\ue6e1',weather_chart:'\ue2bd',calendar:'\ue935','custom:auto-entities':'\ue8ef',grid:'\ue9b0',blank:''};
const css=`
@font-face{font-family:'Material Symbols Outlined';font-style:normal;font-weight:100 700;src:url('/api/rustyhama/frontend/MaterialSymbolsOutlined.ttf') format('truetype');font-display:block}
:host{display:block;color:var(--primary-text-color);background:var(--primary-background-color);min-height:100%}*{box-sizing:border-box}button,select,input,textarea{font:inherit}
header{display:flex;gap:12px;align-items:center;padding:16px 20px;border-bottom:1px solid var(--divider-color)}header h1{font-size:22px;margin:0 auto 0 0}.tabs,.toolbar,.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
button,.doclink{border:0;border-radius:8px;padding:9px 13px;cursor:pointer;background:var(--secondary-background-color);color:inherit;text-decoration:none}button.primary,.tabs button.active{background:var(--primary-color);color:var(--text-primary-color)}button.danger{color:var(--error-color)}button:disabled{opacity:.45;cursor:not-allowed}
main{padding:18px;max-width:1600px;margin:auto}.toolbar{margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr;gap:18px}.grid>.card+ .card{display:none}.card{background:var(--card-background-color);border-radius:12px;padding:16px;box-shadow:var(--ha-card-box-shadow)}
label{display:grid;gap:5px;margin:9px 0}input,select{min-width:0;padding:9px;border:1px solid var(--divider-color);border-radius:7px;background:var(--card-background-color);color:inherit}.error{color:var(--error-color)}.ok{color:var(--success-color)}.muted{opacity:.7;font-size:.9em}.notice{padding:10px 12px;border-left:4px solid var(--warning-color);background:var(--secondary-background-color);margin:10px 0}
.code-editor{height:68vh;display:grid;grid-template-columns:auto 1fr;border:1px solid var(--divider-color);border-radius:8px;overflow:hidden;background:var(--code-editor-background-color,#111);font:14px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.line-numbers{margin:0;padding:12px 10px;text-align:right;white-space:pre;color:#777;background:#181818;user-select:none;overflow:hidden}.code-layer{position:relative;overflow:hidden}.code-layer pre,.code-layer textarea{position:absolute;inset:0;margin:0;padding:12px;border:0;outline:0;white-space:pre;overflow:auto;tab-size:2;font:inherit}.code-layer pre{pointer-events:none;color:#ddd;scrollbar-width:none}.code-layer pre::-webkit-scrollbar{display:none}.code-layer textarea{resize:none;background:transparent;color:transparent;-webkit-text-fill-color:transparent;caret-color:#fff}.code-layer textarea::selection{background:#3d6f9988}.json-key{color:#9cdcfe}.json-string{color:#ce9178}.json-number{color:#b5cea8}.json-literal{color:#569cd6}.json-punctuation{color:#d4d4d4}
.preview-modal{position:fixed;inset:0;z-index:1000;padding:2vh 2vw;background:#000b;display:flex;align-items:center;justify-content:center}.preview-dialog{width:96vw;height:96vh;max-width:1900px;display:flex;flex-direction:column;background:var(--card-background-color);border-radius:14px;box-shadow:0 18px 70px #000c;overflow:hidden}.preview-dialog-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:12px 16px;border-bottom:1px solid var(--divider-color)}.preview-dialog-head h2{margin:0 auto 0 0}.preview-dialog-body{flex:1;min-height:0;padding:12px}.preview-dialog-body>#previewHost{height:100%;display:flex;flex-direction:column}.preview-dialog-body .preview-shell{flex:1;min-height:0;height:auto}.preview-shell{width:100%;height:100%;overflow:auto;overscroll-behavior:contain;background:repeating-conic-gradient(#7771 0 25%,transparent 0 50%) 50%/18px 18px}.preview-canvas{position:relative;min-width:100%;min-height:100%}.device-frame{position:absolute}.device{position:absolute;inset:0 auto auto 0;box-sizing:border-box;flex:0 0 auto;max-width:none;max-height:none;background:var(--db-bg);color:var(--db-text);border:8px solid #292929;border-radius:18px;overflow:hidden;transform-origin:top left;display:flex;flex-direction:column;box-shadow:0 10px 35px #0008}.device-tabs{height:var(--tab-height);display:flex;background:var(--db-bg);flex:none}.device-tab{display:flex;align-items:center;justify-content:center;gap:.28em;min-width:0;padding:0 var(--tab-pad);border:2px solid var(--db-card);color:var(--db-text);border-radius:var(--radius) var(--radius) 0 0;overflow:hidden}.device-tab.active{background:var(--db-accent);border-color:var(--db-accent);color:var(--db-accent-text)}.device-tab.settings{flex:0 0 var(--settings-width)}.device-tab:not(.settings){flex:1}.material{font-family:'Material Symbols Outlined',sans-serif;font-weight:400;font-style:normal;font-variation-settings:'FILL' 0,'wght' 400,'GRAD' 0,'opsz' 24}.device-content{flex:1;overflow:auto;border:2px solid var(--db-accent);border-radius:0 0 var(--radius) var(--radius);background:var(--db-bg)}
.badge-row{display:flex;gap:var(--gap);padding:var(--padding);flex-wrap:wrap}.badge{background:var(--db-card);border-radius:999px;padding:.35em .7em}.dash-grid{display:grid;gap:calc(var(--gap)*2);padding:var(--gap)}.widget{min-width:0;overflow:hidden;background:var(--widget-bg,var(--db-card));border-radius:var(--widget-radius,var(--radius));padding:var(--widget-padding,var(--padding));color:var(--widget-text,var(--db-text));display:flex;flex-direction:column;justify-content:center}.widget.active{background:var(--widget-accent,var(--db-accent));color:var(--widget-accent-text,var(--db-accent-text))}.widget-head{display:flex;gap:.5em;align-items:center}.widget-icon{font-size:1.7em}.widget-title{font-weight:650;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.widget-state{opacity:.78;margin-top:.3em}.controls{display:flex;gap:.45em;align-items:center;margin-top:.55em}.control{background:#ffffff18;border-radius:999px;padding:.25em .55em}.slider{height:.32em;background:#ffffff38;border-radius:99px;overflow:hidden;flex:1}.slider i{display:block;height:100%;background:var(--widget-accent,var(--db-accent))}.media{flex-direction:row;gap:.7em}.coverart{width:4.5em;aspect-ratio:1;border-radius:.5em;background:#0004}.image-placeholder{width:100%;height:100%;min-height:5em;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:.35em;color:var(--widget-text,var(--db-text));background:linear-gradient(135deg,#ffffff0c,#00000020)}.coverart.image-placeholder{width:4.5em;min-height:0;flex:0 0 4.5em}.image-placeholder .material{font-size:2.4em;opacity:.65}.graph svg{width:100%;height:3.6em}.picture{padding:0}.nested{background:transparent;padding:0}.unknown{border:1px dashed var(--db-accent)}
.preview-meta{margin:8px 0 0}.visual-section{border:1px solid var(--divider-color);border-radius:9px;padding:12px;margin:10px 0}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 12px}.theme-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.visual-tab{border:1px solid var(--divider-color);border-radius:9px;padding:12px;margin:12px 0}.visual-tab>summary,.widget-edit>summary{cursor:pointer;font-weight:650}.widget-edit{margin:9px 0;padding:9px;background:var(--secondary-background-color);border-radius:8px}.widget-edit .form-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}.code{font-size:36px;letter-spacing:.16em;font-weight:700}.device-list,.profile-list{display:grid;gap:8px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between;padding:10px;background:var(--secondary-background-color);border-radius:8px}.row-main{min-width:12rem;flex:1}.row-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.qr-result{display:grid;justify-items:center;gap:10px;margin-top:14px}.qr-result ha-qr-code{width:min(320px,80vw);height:min(320px,80vw);background:white;padding:12px}.qr-payload{width:100%;font-family:monospace;font-size:.8em;word-break:break-all}
@media(max-width:950px){.grid,.pair{grid-template-columns:1fr}.preview-shell,.code-editor{height:54vh}.theme-grid,.widget-edit .form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){header{align-items:flex-start;flex-wrap:wrap}.form-grid,.theme-grid,.widget-edit .form-grid{grid-template-columns:1fr}.code-editor{font-size:12px}}
`;

class RustyHamaPanel extends HTMLElement{
 constructor(){super();this.attachShadow({mode:'open'});this.ensureIconFont();this.page='dashboard';this.mode='json';this.view='profile';this.orientation='current';this.previewOpen=false;this.previewZoom='fit';this.model=null;this.profileId='default';this.deviceId='';this.text='';this.message='';this.activeTab=0;this.compiledPreview=null;this.compileTimer=null;}
 ensureIconFont(){if(document.__rustyhamaSymbolFont)return;document.__rustyhamaSymbolFont=new FontFace('Material Symbols Outlined',"url('/api/rustyhama/frontend/MaterialSymbolsOutlined.ttf')",{style:'normal',weight:'400'}).load().then(face=>document.fonts.add(face)).catch(()=>null)}
 set hass(v){this._hass=v;if(!this.model)this.refresh()} get hass(){return this._hass}
 async call(type,data={}){return this.hass.callWS({type:`rustyhama/${type}`,...data})}
 lang(){return String(this.hass?.language||'en').split('-')[0]}
 tr(de,en,fr){return this.lang()==='de'?de:this.lang()==='fr'?fr:en}
 docs(){return DOCS_ROOT+(this.lang()==='en'?'en/':this.lang()==='fr'?'fr/':'')+'components/'}
 esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 clone(v){return JSON.parse(JSON.stringify(v??{}))}
 merge(base,patch){if(!patch||typeof patch!=='object'||Array.isArray(patch))return this.clone(patch);const out=base&&typeof base==='object'&&!Array.isArray(base)?this.clone(base):{};for(const[k,v]of Object.entries(patch)){if(v===null)delete out[k];else out[k]=this.merge(out[k],v)}return out}
 selectedDevice(){return this.model?.devices.find(d=>d.device_id===this.deviceId)} profile(){return this.model?.profiles[this.profileId]}
 source(){const d=this.selectedDevice();if(this.view==='effective')return d?.compiled_config||d?.effective_config||{};if(this.view==='override')return d?.override||{};return this.profile()?.draft||{}}
 previewSource(parsed){if(this.view==='override'){const d=this.selectedDevice();const base=this.model?.profiles[d?.profile_id]?.published||{};return this.merge(base,parsed??this.source())}return parsed??this.source()}
 syncText(){this.text=JSON.stringify(this.source(),null,2);this.compiledPreview=null}
 parse(quiet=false){try{const v=JSON.parse(this.text);if(!quiet)this.message=this.tr('JSON ist gültig','JSON is valid','JSON valide');return v}catch(e){if(!quiet)this.message=`JSON: ${e.message}`;return null}}
 async refresh(){try{this.model=await this.call('get_snapshot');this.profileId=this.model.profiles[this.profileId]?this.profileId:Object.keys(this.model.profiles)[0];this.deviceId=this.deviceId||this.model.devices[0]?.device_id||'';this.syncText();this.render();this.queueCompile()}catch(e){this.message=String(e.message||e);this.render()}}
 async save(){const config=this.parse();if(!config)return this.render();try{if(this.view==='override')await this.call('update_device',{device_id:this.deviceId,override:config});else if(this.view==='profile')await this.call('save_profile',{profile_id:this.profileId,name:this.profile().name,config});else throw Error(this.tr('Effektive Konfiguration ist schreibgeschützt','Effective configuration is read-only','La configuration effective est en lecture seule'));this.message=this.view==='override'?this.tr('Gespeichert und an das Gerät verteilt','Saved and deployed to the device','Enregistré et déployé sur l’appareil'):this.tr('Entwurf gespeichert','Draft saved','Brouillon enregistré');await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 async publish(){try{const r=await this.call('publish_profile',{profile_id:this.profileId});this.message=`${this.tr('Veröffentlichte Revision','Published revision','Révision publiée')} ${r.revision}`;await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 async createProfile(){const id=this.shadowRoot.querySelector('#newProfileId')?.value.trim(),name=this.shadowRoot.querySelector('#newProfileName')?.value.trim(),sourceId=this.shadowRoot.querySelector('#newProfileSource')?.value||this.profileId;if(!/^[a-z0-9][a-z0-9_-]*$/.test(id||'')){this.message=this.tr('Profil-ID: nur a-z, 0-9, _ und -','Profile ID: use only a-z, 0-9, _ and -','ID de profil : uniquement a-z, 0-9, _ et -');return this.render()}if(this.model.profiles[id]){this.message=this.tr('Diese Profil-ID existiert bereits','This profile ID already exists','Cet ID de profil existe déjà');return this.render()}const source=this.model.profiles[sourceId]?.draft||{schema_version:1,tabs:[{id:'overview',title:'Overview',columns:2,widgets:[]}]};try{await this.call('save_profile',{profile_id:id,name:name||id,config:this.clone(source)});this.profileId=id;this.page='dashboard';this.view='profile';this.message=this.tr('Profil erstellt','Profile created','Profil créé');await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 async renameProfile(id){const input=this.shadowRoot.querySelector(`[data-profile-name="${id}"]`),profile=this.model.profiles[id];if(!input||!profile)return;try{await this.call('save_profile',{profile_id:id,name:input.value.trim()||id,config:profile.draft});this.message=this.tr('Profil umbenannt','Profile renamed','Profil renommé');await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 async deleteProfile(id){try{await this.call('delete_profile',{profile_id:id});if(this.profileId===id)this.profileId='default';this.message=this.tr('Profil gelöscht','Profile deleted','Profil supprimé');await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 async assignDeviceProfile(deviceId,profileId){try{await this.call('update_device',{device_id:deviceId,profile_id:profileId});this.message=this.tr('Geräteprofil gespeichert und verteilt','Device profile saved and deployed','Profil de l’appareil enregistré et déployé');await this.refresh()}catch(e){this.message=String(e.message||e);this.render()}}
 setDraft(config){this.text=JSON.stringify(config,null,2);this.compiledPreview=null;if(this.view==='profile')this.model.profiles[this.profileId].draft=config;else if(this.view==='override')this.selectedDevice().override=config;this.render();this.queueCompile()}
 mutate(fn){const c=this.clone(this.parse(true)||this.source());fn(c);this.setDraft(c)}
 queueCompile(){clearTimeout(this.compileTimer);const parsed=this.parse(true);if(!parsed){this.compiledPreview=null;return}const source=this.previewSource(parsed);this.compileTimer=setTimeout(async()=>{try{const r=await this.call('compile_preview',{config:source,...(this.deviceId?{device_id:this.deviceId}:{})});this.compiledPreview=r.config;this.renderPreviewOnly()}catch(e){this.message=String(e.message||e);this.setStatus()}},220)}
 highlightJson(text){const re=/("(?:\\.|[^"\\])*")(?=\s*:)|("(?:\\.|[^"\\])*")|(-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)|\b(true|false|null)\b|([{}\[\],:])/g;let out='',last=0,m;while((m=re.exec(text))){out+=this.esc(text.slice(last,m.index));const cls=m[1]?'json-key':m[2]?'json-string':m[3]?'json-number':m[4]?'json-literal':'json-punctuation';out+=`<span class="${cls}">${this.esc(m[0])}</span>`;last=re.lastIndex}return out+this.esc(text.slice(last))}
 editor(){const lines=Array.from({length:Math.max(1,this.text.split('\n').length)},(_,i)=>i+1).join('\n');return `<div class="code-editor"><pre class="line-numbers" id="lines">${lines}</pre><div class="code-layer"><pre id="highlight">${this.highlightJson(this.text)}\n</pre><textarea id="editor" aria-label="JSON" spellcheck="false" ${this.view==='effective'?'readonly':''}>${this.esc(this.text)}</textarea></div></div>`}
 theme(config){const light=config?.theme==='light';const base={background_color:light?'#f5f5f5':'#121212',primary_color:light?'#ffffff':'#2d2d2d',accent_color:'#2196f3',text_color:light?'#000000':'#ffffff',accent_text_color:light?'#ffffff':'#000000',corner_radius:12,ui_scale:1.18,padding:10,gap:6};return typeof config?.theme==='object'?{...base,...config.theme}:base}
 state(w){const id=w.entity_id||w.entity;return id?this.hass?.states?.[id]:null}
 title(w,s){return w.title||w.name||s?.attributes?.friendly_name||String(w.entity_id||w.entity||w.type||'Widget').replace(/^.*\./,'').replaceAll('_',' ')}
 icon(w,type){return w.icon||(String(this.state(w)?.state)==='on'?w.icon_on:w.icon_off)||TYPE_ICONS[type]||'\ue8ef'}
 pct(v,min=0,max=100){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(100,(n-min)*100/(max-min))):0}
 widgetStyle(w,t,d){const o=typeof w.theme==='object'?w.theme:{};return `--widget-bg:${o.primary_color||t.primary_color};--widget-text:${o.text_color||t.text_color};--widget-accent:${o.accent_color||t.accent_color};--widget-accent-text:${o.accent_text_color||t.accent_text_color};--widget-radius:${Number(o.corner_radius??t.corner_radius)*d}px;--widget-padding:${Number(o.padding??t.padding)*d}px`}
 renderWidget(w,ctx){const type=String(w.type||'label').toLowerCase(),s=this.state(w),st=s?.state??'',a=s?.attributes||{},title=this.title(w,s),icon=this.icon(w,type),style=this.widgetStyle(w,ctx.theme,ctx.density);const head=`<div class="widget-head"><span class="widget-icon material">${this.esc(icon)}</span><span class="widget-title">${this.esc(title)}</span></div>`;let body='';let cls='';
  if(type==='blank')return `<div class="widget" style="${style};background:transparent"></div>`;
  if(type==='clock'||type==='datetime'){const now=new Date(),time=now.toLocaleTimeString(this.lang(),{hour:'2-digit',minute:'2-digit',second:w.time_format?.includes('ss')?'2-digit':undefined}),date=now.toLocaleDateString(this.lang(),{weekday:'long',day:'2-digit',month:'long',year:'numeric'});body=`<div style="font-size:2em;font-weight:650">${time}</div><div class="widget-state">${this.esc(date)}</div>`}
  else if(['light','switch','button'].includes(type)){cls=st==='on'?' active':'';body=`${head}<div class="widget-state">${this.esc(st||'unavailable')}</div>`}
  else if(type==='label'){body=`${head}<div class="widget-state" style="font-size:1.35em">${this.esc(st)}${this.esc(w.unit??a.unit_of_measurement??'')}</div>`}
  else if(type==='select'||type==='entity_select'){body=`${head}<div class="control">${this.esc(st||a.options?.[0]||'—')} ▾</div>`}
  else if(type==='cover'){const p=Number(a.current_position??0);body=`${head}<div class="controls"><span class="control">▲</span><span class="control">■</span><span class="control">▼</span></div><div class="controls"><div class="slider"><i style="width:${this.pct(p)}%"></i></div><span>${p}%</span></div>`}
  else if(type==='fan'){const p=Number(a.percentage??0);body=`${head}<div class="widget-state">${this.esc(st)}</div><div class="controls"><span class="control">−</span><div class="slider"><i style="width:${this.pct(p)}%"></i></div><span>${p}%</span><span class="control">+</span></div>`}
  else if(type==='climate'||type==='thermostat'){const cur=a.current_temperature??'—',target=a.temperature??a.target_temp_low??'—';body=`${head}<div class="controls"><b>${this.esc(target)}°</b><span class="control">−</span><span>Ist ${this.esc(cur)}°</span><span class="control">+</span></div><div class="widget-state">${this.esc(st)}${a.current_humidity!=null?` · ${a.current_humidity}%`:''}</div>`}
  else if(type==='media_player'||type==='media'){body=`<div class="coverart image-placeholder material">${TYPE_ICONS.media_player}</div><div style="min-width:0;flex:1">${head}<div class="widget-state">${this.esc(a.media_title||st||'')}</div><div class="controls"><span>◀</span><span class="control">${st==='playing'?'Ⅱ':'▶'}</span><span>▶</span><div class="slider"><i style="width:${this.pct(a.media_position??0,0,a.media_duration??100)}%"></i></div></div></div>`;cls=' media'}
  else if(['camera','picture','image','video'].includes(type)){body=`<div class="image-placeholder"><span class="material">${this.esc(TYPE_ICONS[type]||TYPE_ICONS.picture)}</span><span>${this.esc(title)}</span></div>`;cls=' picture'}
  else if(['history_graph','sensor_graph','graph','mini_graph','mini_graph_card','mini-graph-card','custom:mini-graph-card'].includes(type)){body=`${head}<div class="widget-state">${this.esc(st)} ${this.esc(a.unit_of_measurement||'')}</div><svg viewBox="0 0 240 55" preserveAspectRatio="none"><polyline points="0,42 35,35 70,39 105,17 140,26 175,10 210,23 240,12" fill="none" stroke="${ctx.theme.accent_color}" stroke-width="3"/></svg>`;cls=' graph'}
  else if(type.includes('weather')){body=`${head}<div style="font-size:1.8em">${this.esc(a.temperature??st)}${a.temperature!=null?'°':''}</div><div class="widget-state">${this.esc(st)}${a.humidity!=null?` · ${a.humidity}%`:''}</div>`}
  else if(type==='calendar'){body=`${head}<div class="widget-state">${this.esc(a.message||st||'Keine Termine')}</div><div>${this.esc(a.start_time||'')}</div>`}
  else if(type==='assist_button'||type==='voice_assistant_button'||type==='push_to_talk'){body=`${head}<div class="widget-state">${this.tr('Zum Sprechen halten','Hold to talk','Maintenir pour parler')}</div>`}
  else if(type==='grid'){body=this.renderGrid(w,ctx);cls=' nested'}
  else if(type.includes('auto-entities')||type==='auto_entities'){body=`${head}${(w.entities||[]).slice(0,8).map(e=>{const x=typeof e==='string'?{entity:e}:e,es=this.hass?.states?.[x.entity];return `<div class="controls"><span>${this.esc(x.name||es?.attributes?.friendly_name||x.entity)}</span><b style="margin-left:auto">${this.esc(es?.state||'')}</b></div>`}).join('')}`}
  else{body=`${head}<div class="widget-state">${this.tr('Erweiterter Block','Advanced block','Bloc avancé')}</div>`;cls=' unknown'}
  return `<div class="widget${cls}" style="${style}">${body}</div>`}
 renderGrid(tab,ctx){const cols=Math.max(1,Number(tab.columns||1)),gap=Number(tab.gap??tab.margin??ctx.theme.gap)*ctx.density,cell=Number(tab.cell_height||tab.row_height||0)*ctx.density;return `<div class="dash-grid" style="grid-template-columns:repeat(${cols},minmax(0,1fr));gap:${gap*2}px;${cell?`grid-auto-rows:${cell}px`:''}">${(tab.widgets||[]).map(w=>{const cs=Math.min(cols,Math.max(1,Number(w.colspan||w.col_span||1))),rs=Math.max(1,Number(w.rowspan||w.row_span||1)),pos=`grid-column:${w.col!=null?Number(w.col)+1:'auto'} / span ${cs};grid-row:${w.row!=null?Number(w.row)+1:'auto'} / span ${rs};min-height:${Number(w.min_height||0)*ctx.density}px`;return `<div style="${pos}">${this.renderWidget(w,ctx)}</div>`}).join('')}</div>`}
 preview(){const d=this.selectedDevice(),config=this.compiledPreview||this.previewSource(this.parse(true)||undefined),display=d?.display||{};let width=Number(display.usable_width_px||display.activity_width_px||1280),height=Number(display.usable_height_px||display.activity_height_px||800);if(this.orientation!=='current'&&((this.orientation==='portrait')!==(height>=width)))[width,height]=[height,width];const density=Number(display.density||display.density_dpi/160||1),font=Number(display.font_scale||1),theme=this.theme(config),tabs=config.tabs||[],index=Math.min(this.activeTab,Math.max(0,tabs.length-1)),tab=tabs[index]||{columns:1,widgets:[]},ctx={density,font,theme};const radius=Number(theme.corner_radius)*density,padding=Number(theme.padding)*density,gap=Number(theme.gap)*density,scale=Number(theme.ui_scale||1);const variables=`--db-bg:${theme.background_color};--db-card:${theme.primary_color};--db-accent:${theme.accent_color};--db-text:${theme.text_color};--db-accent-text:${theme.accent_text_color};--radius:${radius}px;--padding:${padding}px;--gap:${gap}px;--tab-height:${Number(config.tab_height||45)*density}px;--tab-pad:${Number(config.tab_padding_horizontal||12)*density}px;--settings-width:${Number(config.settings_tab_width||52)*density}px`;
  const tabbar=`<div class="device-tabs">${tabs.map((t,i)=>`<div class="device-tab ${i===index?'active':''}" data-preview-tab="${i}">${t.icon?`<span class="material">${this.esc(t.icon)}</span>`:''}<span>${this.esc(t.title||t.id)}</span></div>`).join('')}<div class="device-tab settings material">\ue8b8</div></div>`;const badges=tab.show_badges!==false&&(tab.badges||[]).length?`<div class="badge-row">${tab.badges.map(b=>`<span class="badge">${this.esc(this.title(b,this.state(b)))} · ${this.esc(this.state(b)?.state||'')}</span>`).join('')}</div>`:'';return `<div class="preview-shell" id="preview"><div class="preview-canvas" id="previewCanvas"><div class="device-frame" id="deviceFrame"><div class="device" id="devicePreview" style="width:${width}px;height:${height}px;font-size:${14*density*font*scale}px;${variables}">${tabbar}<div class="device-content">${badges}${tab.type==='music_assistant'?this.renderWidget({type:'media_player',title:'Music Assistant'},ctx):this.renderGrid(tab,ctx)}</div></div></div></div></div><p class="muted preview-meta">${d?`${width} × ${height}px · ${display.density_dpi||Math.round(density*160)} dpi · font ${font}`:this.tr('Generische, nicht gerätespezifische Vorschau','Generic, non-device-specific preview','Aperçu générique non spécifique à l’appareil')}${this.compiledPreview?' · server compiled':''}</p>`}
 fitPreview(){requestAnimationFrame(()=>{const wrap=this.shadowRoot.querySelector('#preview'),canvas=this.shadowRoot.querySelector('#previewCanvas'),frame=this.shadowRoot.querySelector('#deviceFrame'),dev=this.shadowRoot.querySelector('#devicePreview');if(!wrap||!canvas||!frame||!dev)return;dev.style.transform='none';const naturalWidth=dev.offsetWidth,naturalHeight=dev.offsetHeight,availableWidth=Math.max(1,wrap.clientWidth-28),availableHeight=Math.max(1,wrap.clientHeight-28),fit=Math.min(availableWidth/naturalWidth,availableHeight/naturalHeight,1),requested=this.previewZoom==='fit'?fit:Number(this.previewZoom),scale=Number.isFinite(requested)&&requested>0?requested:fit,width=Math.max(1,Math.round(naturalWidth*scale)),height=Math.max(1,Math.round(naturalHeight*scale)),canvasWidth=Math.max(wrap.clientWidth,width+28),canvasHeight=Math.max(wrap.clientHeight,height+28),left=Math.max(14,Math.round((canvasWidth-width)/2)),top=Math.max(14,Math.round((canvasHeight-height)/2));dev.style.transform=`scale(${scale})`;frame.style.width=`${width}px`;frame.style.height=`${height}px`;frame.style.left=`${left}px`;frame.style.top=`${top}px`;canvas.style.width=`${canvasWidth}px`;canvas.style.height=`${canvasHeight}px`;wrap.scrollLeft=Math.max(0,left+width/2-wrap.clientWidth/2);wrap.scrollTop=Math.max(0,top+height/2-wrap.clientHeight/2)})}
 renderPreviewOnly(){const host=this.shadowRoot.querySelector('#previewHost');if(!host)return;host.innerHTML=this.preview();host.querySelectorAll('[data-preview-tab]').forEach(b=>b.onclick=()=>{this.activeTab=Number(b.dataset.previewTab);this.renderPreviewOnly()});this.fitPreview()}
 previewModal(){if(!this.previewOpen)return '';return `<div class="preview-modal" id="previewBackdrop"><section class="preview-dialog" role="dialog" aria-modal="true"><div class="preview-dialog-head"><h2>${this.tr('Gerätevorschau','Device preview','Aperçu de l’appareil')}</h2><select id="orientation"><option value="current">${this.tr('Aktuelle Ausrichtung','Current orientation','Orientation actuelle')}</option><option value="portrait" ${this.orientation==='portrait'?'selected':''}>Portrait</option><option value="landscape" ${this.orientation==='landscape'?'selected':''}>Landscape</option></select><select id="previewZoom"><option value="fit" ${this.previewZoom==='fit'?'selected':''}>${this.tr('Einpassen','Fit','Ajuster')}</option>${[[.25,'25 %'],[.5,'50 %'],[.75,'75 %'],[1,'100 %']].map(([v,l])=>`<option value="${v}" ${String(this.previewZoom)===String(v)?'selected':''}>${l}</option>`).join('')}</select><button id="previewClose">${this.tr('Schließen','Close','Fermer')}</button></div><div class="preview-dialog-body"><div id="previewHost">${this.preview()}</div></div></section></div>`}
 visual(){const c=this.parse(true)||this.source();if(this.view!=='profile')return `<div class="notice">${this.tr('Der visuelle Editor bearbeitet vollständige Profile. Geräte-Overrides sind Merge-Patches und bleiben deshalb im JSON-Editor; rechts wird trotzdem die zusammengeführte Konfiguration angezeigt.','The visual editor edits complete profiles. Device overrides are merge patches and remain in the JSON editor; the merged configuration is still shown on the right.','L’éditeur visuel modifie des profils complets. Les substitutions d’appareil sont des correctifs de fusion et restent donc dans l’éditeur JSON ; la configuration fusionnée est affichée à droite.')}</div>`;const t=this.theme(c);return `<section class="visual-section"><h3>${this.tr('Theme','Theme','Thème')}</h3><div class="form-grid theme-grid">${['background_color','primary_color','accent_color','text_color','accent_text_color'].map(k=>`<label>${k}<input type="color" data-theme="${k}" value="${this.esc(t[k])}"></label>`).join('')}${[['corner_radius',0,64],['ui_scale',.85,1.8],['padding',0,48],['gap',0,32]].map(([k,min,max])=>`<label>${k}<input type="number" step="0.1" min="${min}" max="${max}" data-theme="${k}" value="${t[k]}"></label>`).join('')}</div></section><h3>Tabs</h3>${(c.tabs||[]).map((tab,ti)=>`<details class="visual-tab" open><summary>${this.esc(tab.title||tab.id||`Tab ${ti+1}`)}</summary><div class="actions"><button data-tab-move="${ti}" data-delta="-1" ${ti===0?'disabled':''}>↑</button><button data-tab-move="${ti}" data-delta="1" ${ti===c.tabs.length-1?'disabled':''}>↓</button><button class="danger" data-tab-delete="${ti}">${this.tr('Löschen','Delete','Supprimer')}</button></div><div class="form-grid">${this.field('ID','id',tab.id,ti)}${this.field(this.tr('Titel','Title','Titre'),'title',tab.title,ti)}${this.field('Icon','icon',tab.icon,ti)}${this.numberField(this.tr('Spalten','Columns','Colonnes'),'columns',tab.columns||1,ti,1,12)}${this.numberField('cell_height','cell_height',tab.cell_height??'',ti,0,2000)}${this.numberField('gap','gap',tab.gap??'',ti,0,32)}</div><h4>Widgets</h4>${(tab.widgets||[]).map((w,wi)=>this.widgetEditor(w,ti,wi)).join('')}<div class="actions"><select data-new-type="${ti}">${TYPES.map(x=>`<option>${this.esc(x)}</option>`).join('')}</select><button data-widget-add="${ti}">${this.tr('Widget hinzufügen','Add widget','Ajouter un widget')}</button></div></details>`).join('')}<button id="addTab">${this.tr('Tab hinzufügen','Add tab','Ajouter un onglet')}</button><div class="notice">${this.tr('Alle nicht dargestellten erweiterten Felder bleiben unverändert erhalten und können jederzeit im JSON-Editor bearbeitet werden.','All advanced fields not shown here are preserved unchanged and can always be edited in the JSON editor.','Tous les champs avancés non affichés restent inchangés et peuvent toujours être modifiés dans l’éditeur JSON.')}</div>`}
 field(label,key,value,ti,wi){return `<label>${label}<input data-field="${key}" data-tab="${ti}" ${wi!=null?`data-widget="${wi}"`:''} value="${this.esc(value||'')}"></label>`}
 numberField(label,key,value,ti,min,max,wi){return `<label>${label}<input type="number" min="${min}" max="${max}" data-field="${key}" data-number data-tab="${ti}" ${wi!=null?`data-widget="${wi}"`:''} value="${this.esc(value)}"></label>`}
 widgetEditor(w,ti,wi){return `<details class="widget-edit"><summary>${this.esc(w.title||w.id||w.type)} · ${this.esc(w.type)}</summary><div class="actions"><button data-widget-move="${ti}:${wi}" data-delta="-1" ${wi===0?'disabled':''}>↑</button><button data-widget-move="${ti}:${wi}" data-delta="1">↓</button><button class="danger" data-widget-delete="${ti}:${wi}">${this.tr('Löschen','Delete','Supprimer')}</button></div><div class="form-grid">${this.field('ID','id',w.id,ti,wi)}<label>Type<select data-field="type" data-tab="${ti}" data-widget="${wi}">${TYPES.map(x=>`<option ${x===w.type?'selected':''}>${this.esc(x)}</option>`).join('')}</select></label>${this.field(this.tr('Titel','Title','Titre'),'title',w.title,ti,wi)}${this.field('Entity','entity',w.entity||w.entity_id,ti,wi)}${this.numberField('row','row',w.row??'',ti,0,99,wi)}${this.numberField('col','col',w.col??'',ti,0,99,wi)}${this.numberField('rowspan','rowspan',w.rowspan||w.row_span||1,ti,1,99,wi)}${this.numberField('colspan','colspan',w.colspan||w.col_span||1,ti,1,12,wi)}${this.numberField('min_height','min_height',w.min_height??'',ti,0,2000,wi)}${['clock','datetime'].includes(w.type)?this.field('time_format','time_format',w.time_format||'HH:mm',ti,wi)+this.field('date_format','date_format',w.date_format||'EEEE, dd. MMMM yyyy',ti,wi):''}</div></details>`}
 dashboard(){if(!this.model)return '<p>Loading…</p>';const d=this.selectedDevice(),good=/gültig|valid|valide|gespeichert|saved|enregistré|Revision|révision|distributed|verteilt|déployé/i.test(this.message);return `<div class="toolbar"><select id="profile" title="${this.tr('Profil','Profile','Profil')}">${Object.entries(this.model.profiles).map(([id,p])=>`<option value="${this.esc(id)}" ${id===this.profileId?'selected':''}>${this.esc(p.name)}</option>`).join('')}</select><select id="device" title="${this.tr('Vorschaugerät','Preview device','Appareil d’aperçu')}"><option value="">${this.tr('Generisches Tablet','Generic tablet','Tablette générique')}</option>${this.model.devices.map(x=>`<option value="${x.device_id}" ${x.device_id===this.deviceId?'selected':''}>${this.esc(x.name)}</option>`).join('')}</select><select id="view"><option value="profile">${this.tr('Profilentwurf','Profile draft','Brouillon du profil')}</option><option value="override" ${this.view==='override'?'selected':''} ${d?'':'disabled'}>${this.tr('Geräte-Override','Device override','Surcharge de l’appareil')}</option><option value="effective" ${this.view==='effective'?'selected':''} ${d?'':'disabled'}>${this.tr('Effektive Konfiguration','Effective config','Configuration effective')}</option></select><button id="jsonMode" class="${this.mode==='json'?'primary':''}">JSON</button><button id="visualMode" class="${this.mode==='visual'?'primary':''}">${this.tr('Visuell','Visual','Visuel')}</button><button id="previewButton">${this.tr('Vorschau','Preview','Aperçu')}</button><button id="save" class="primary" ${this.view==='effective'?'disabled':''}>${this.view==='override'?this.tr('Speichern & verteilen','Save & deploy','Enregistrer et déployer'):this.tr('Entwurf speichern','Save draft','Enregistrer le brouillon')}</button>${this.view==='profile'?`<button id="publish">${this.tr('Veröffentlichen','Publish','Publier')}</button>`:''}<span id="status" class="${good?'ok':'error'}">${this.esc(this.message)}</span>${d?`<span class="muted">rev ${d.acknowledged_revision}/${d.config_revision} · ${d.online?'online':'offline'}</span>`:''}</div><div class="grid"><section class="card">${this.mode==='json'?this.editor():this.visual()}</section></div>${this.previewModal()}`}
 profiles(){const profiles=Object.entries(this.model?.profiles||{}),rows=profiles.map(([id,p])=>{const assigned=(this.model.devices||[]).filter(d=>d.profile_id===id).length;return `<div class="row"><div class="row-main"><b>${this.esc(id)}</b><input data-profile-name="${this.esc(id)}" value="${this.esc(p.name)}"><div class="muted">${assigned} ${this.tr('Gerät(e)','device(s)','appareil(s)')}</div></div><div class="row-actions"><button data-profile-open="${this.esc(id)}">${this.tr('Bearbeiten','Edit','Modifier')}</button><button data-profile-rename="${this.esc(id)}">${this.tr('Umbenennen','Rename','Renommer')}</button><button class="danger" data-profile-delete="${this.esc(id)}" ${id==='default'||assigned?'disabled':''}>${this.tr('Löschen','Delete','Supprimer')}</button></div></div>`}).join('');return `<div class="pair"><section class="card"><h2>${this.tr('Profil erstellen','Create profile','Créer un profil')}</h2><label>${this.tr('Profil-ID','Profile ID','ID du profil')}<input id="newProfileId" placeholder="wall_tablet"></label><label>${this.tr('Anzeigename','Display name','Nom affiché')}<input id="newProfileName" placeholder="Wall tablet"></label><label>${this.tr('Kopieren von','Copy from','Copier depuis')}<select id="newProfileSource">${profiles.map(([id,p])=>`<option value="${this.esc(id)}">${this.esc(p.name)}</option>`).join('')}</select></label><button id="profileCreate" class="primary">${this.tr('Profil erstellen','Create profile','Créer le profil')}</button><p class="muted">${this.tr('Profile enthalten vollständige Dashboards. Geräte-Overrides bleiben RFC-7396-Merge-Patches.','Profiles contain complete dashboards. Device overrides remain RFC 7396 merge patches.','Les profils contiennent des tableaux de bord complets. Les surcharges d’appareil restent des correctifs RFC 7396.')}</p></section><section class="card"><h2>${this.tr('Profile','Profiles','Profils')}</h2><div class="profile-list">${rows}</div></section></div>`}
 devices(){const profileOptions=d=>Object.entries(this.model?.profiles||{}).map(([id,p])=>`<option value="${this.esc(id)}" ${d.profile_id===id?'selected':''}>${this.esc(p.name)}</option>`).join(''),rows=(this.model?.devices||[]).map(d=>`<div class="row"><div class="row-main"><b>${this.esc(d.name)}</b><div class="muted">${d.online?'online':'offline'} · rev ${d.acknowledged_revision}/${d.config_revision} · ${this.esc(d.area_id||'no area')}</div></div><div class="row-actions"><select data-device-profile="${d.device_id}">${profileOptions(d)}</select><button data-device-profile-save="${d.device_id}">${this.tr('Profil zuweisen','Assign profile','Attribuer le profil')}</button><button data-override-open="${d.device_id}">${this.tr('Override bearbeiten','Edit override','Modifier la surcharge')}</button></div></div>`).join('');return `<div class="pair"><section class="card"><h2>${this.tr('Gerät koppeln','Pair device','Associer un appareil')}</h2><label>Name<input id="pairName" value="RustyHAMA"></label><label>Profile<select id="pairProfile">${Object.entries(this.model?.profiles||{}).map(([id,p])=>`<option value="${id}">${this.esc(p.name)}</option>`).join('')}</select></label><label>Area ID<input id="pairArea"></label><label>${this.tr('Public-Key-Pin (optional)','Public-key pin (optional)','Empreinte de clé publique (facultative)')}<input id="pairPublicKeyPin" placeholder="sha256/…"></label><button id="pairCreate" class="primary">${this.tr('Pairing erstellen','Create pairing','Créer l’association')}</button><div id="pairResult"></div></section><section class="card"><h2>${this.tr('Geräte','Devices','Appareils')}</h2><div class="device-list">${rows||'<p>No paired devices.</p>'}</div></section></div>`}
 providers(){return `<section class="card"><h2>Provider connections</h2><p>Keys are stored only in private Home Assistant storage and never returned to this panel or a device.</p><label>ID<input id="providerId"></label><label>Type<select id="providerType"><option>immich</option><option>music_assistant</option></select></label><label>URL<input id="providerUrl"></label><label>API key / token<input id="providerKey" type="password" autocomplete="new-password"></label><button id="providerSave" class="primary">Save provider</button><h3>Configured</h3>${Object.entries(this.model?.providers||{}).map(([id,p])=>`<div class="row"><b>${this.esc(id)}</b><span>${this.esc(p.type)} · ${this.esc(p.url)}</span></div>`).join('')}</section>`}
 render(){this.shadowRoot.innerHTML=`<style>${css}</style><header><h1>RustyHAMA</h1><a class="doclink" href="${this.docs()}" target="_blank" rel="noreferrer">${this.tr('Widget-Dokumentation','Widget documentation','Documentation des widgets')} ↗</a><nav class="tabs"><button data-page="dashboard" class="${this.page==='dashboard'?'active':''}">Dashboard</button><button data-page="profiles" class="${this.page==='profiles'?'active':''}">${this.tr('Profile','Profiles','Profils')}</button><button data-page="devices" class="${this.page==='devices'?'active':''}">${this.tr('Geräte','Devices','Appareils')}</button><button data-page="providers" class="${this.page==='providers'?'active':''}">Providers</button></nav></header><main>${this.page==='dashboard'?this.dashboard():this.page==='profiles'?this.profiles():this.page==='devices'?this.devices():this.providers()}</main>`;this.bind();this.renderPreviewOnly()}
 setStatus(){const s=this.shadowRoot.querySelector('#status');if(s){s.textContent=this.message;s.className=this.parse(true)?'ok':'error'}}
 bind(){const q=s=>this.shadowRoot.querySelector(s);this.shadowRoot.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{this.page=b.dataset.page;this.render()});if(this.page==='dashboard'&&this.model){const ed=q('#editor');if(ed){const sync=()=>{const highlight=q('#highlight'),lines=q('#lines');highlight.innerHTML=this.highlightJson(ed.value)+'\n';lines.textContent=Array.from({length:Math.max(1,ed.value.split('\n').length)},(_,i)=>i+1).join('\n');highlight.scrollLeft=ed.scrollLeft;highlight.scrollTop=ed.scrollTop;lines.scrollTop=ed.scrollTop};ed.oninput=()=>{this.text=ed.value;this.compiledPreview=null;this.parse();sync();this.setStatus();this.renderPreviewOnly();this.queueCompile()};ed.onscroll=sync;ed.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const a=ed.selectionStart,b=ed.selectionEnd;ed.setRangeText('  ',a,b,'end');ed.dispatchEvent(new Event('input'))}}}
   q('#profile').onchange=e=>{this.profileId=e.target.value;this.view='profile';this.activeTab=0;this.syncText();this.render();this.queueCompile()};q('#device').onchange=e=>{this.deviceId=e.target.value;const selected=this.selectedDevice();if(selected)this.profileId=selected.profile_id;this.compiledPreview=null;if(this.view!=='profile')this.syncText();this.render();this.queueCompile()};q('#view').onchange=e=>{this.view=e.target.value;this.mode=e.target.value==='effective'?'json':this.mode;this.activeTab=0;this.syncText();this.render();this.queueCompile()};q('#jsonMode').onclick=()=>{this.mode='json';this.render()};q('#visualMode').onclick=()=>{this.mode='visual';this.render()};q('#previewButton').onclick=()=>{this.previewOpen=true;this.render()};q('#previewClose')?.addEventListener('click',()=>{this.previewOpen=false;this.render()});q('#previewBackdrop')?.addEventListener('click',e=>{if(e.target.id==='previewBackdrop'){this.previewOpen=false;this.render()}});q('#save').onclick=()=>this.save();q('#publish')?.addEventListener('click',()=>this.publish());q('#orientation')?.addEventListener('change',e=>{this.orientation=e.target.value;this.renderPreviewOnly()});q('#previewZoom')?.addEventListener('change',e=>{this.previewZoom=e.target.value;this.fitPreview()});q('#addTab')?.addEventListener('click',()=>this.mutate(c=>{c.tabs=c.tabs||[];c.tabs.push({id:`tab_${Date.now()}`,title:'New tab',columns:2,widgets:[]})}));
   this.shadowRoot.querySelectorAll('[data-theme]').forEach(x=>x.onchange=()=>this.mutate(c=>{if(typeof c.theme!=='object')c.theme=this.theme(c);c.theme[x.dataset.theme]=x.type==='number'?Number(x.value):x.value}));this.shadowRoot.querySelectorAll('[data-field]').forEach(x=>x.onchange=()=>this.mutate(c=>{const t=c.tabs[Number(x.dataset.tab)],target=x.dataset.widget==null?t:t.widgets[Number(x.dataset.widget)],key=x.dataset.field;if(x.value===''&&x.hasAttribute('data-number'))delete target[key];else target[key]=x.hasAttribute('data-number')?Number(x.value):x.value;if(key==='entity')delete target.entity_id}));this.shadowRoot.querySelectorAll('[data-tab-delete]').forEach(x=>x.onclick=()=>this.mutate(c=>c.tabs.splice(Number(x.dataset.tabDelete),1)));this.shadowRoot.querySelectorAll('[data-tab-move]').forEach(x=>x.onclick=()=>this.mutate(c=>{const i=Number(x.dataset.tabMove),j=i+Number(x.dataset.delta);[c.tabs[i],c.tabs[j]]=[c.tabs[j],c.tabs[i]]}));this.shadowRoot.querySelectorAll('[data-widget-add]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.widgetAdd),type=q(`[data-new-type="${i}"]`).value;this.mutate(c=>c.tabs[i].widgets.push({id:`${type.replace(/[^a-z0-9]+/g,'_')}_${Date.now()}`,type,...(!['clock','blank','assist_button','grid'].includes(type)?{entity:'light.example'}:{})}))});this.shadowRoot.querySelectorAll('[data-widget-delete]').forEach(x=>x.onclick=()=>{const[t,w]=x.dataset.widgetDelete.split(':').map(Number);this.mutate(c=>c.tabs[t].widgets.splice(w,1))});this.shadowRoot.querySelectorAll('[data-widget-move]').forEach(x=>x.onclick=()=>{const[t,w]=x.dataset.widgetMove.split(':').map(Number),j=w+Number(x.dataset.delta);this.mutate(c=>{if(j<0||j>=c.tabs[t].widgets.length)return;[c.tabs[t].widgets[w],c.tabs[t].widgets[j]]=[c.tabs[t].widgets[j],c.tabs[t].widgets[w]]})})}
  if(this.page==='profiles'){q('#profileCreate').onclick=()=>this.createProfile();this.shadowRoot.querySelectorAll('[data-profile-open]').forEach(b=>b.onclick=()=>{this.profileId=b.dataset.profileOpen;this.view='profile';this.page='dashboard';this.syncText();this.render();this.queueCompile()});this.shadowRoot.querySelectorAll('[data-profile-rename]').forEach(b=>b.onclick=()=>this.renameProfile(b.dataset.profileRename));this.shadowRoot.querySelectorAll('[data-profile-delete]').forEach(b=>b.onclick=()=>this.deleteProfile(b.dataset.profileDelete))}
  if(this.page==='devices'){q('#pairCreate').onclick=async()=>{try{const r=await this.call('create_pairing',{name:q('#pairName').value,profile_id:q('#pairProfile').value,area_id:q('#pairArea').value||null,public_key_pin:q('#pairPublicKeyPin').value||''}),qr=JSON.stringify({url:location.origin,qr_token:r.qr_token,public_key_pin:r.public_key_pin}),result=q('#pairResult');result.innerHTML=`<div class="qr-result"><p class="code">${r.code}</p><p>${this.tr('Zehn Minuten gültig','Valid for ten minutes','Valable dix minutes')}</p><code class="qr-payload">${this.esc(qr)}</code></div>`;const qrCode=document.createElement('ha-qr-code');qrCode.data=qr;qrCode.value=qr;result.querySelector('.qr-result').insertBefore(qrCode,result.querySelector('.qr-payload'))}catch(e){q('#pairResult').textContent=e.message}};this.shadowRoot.querySelectorAll('[data-device-profile-save]').forEach(b=>b.onclick=()=>this.assignDeviceProfile(b.dataset.deviceProfileSave,q(`[data-device-profile="${b.dataset.deviceProfileSave}"]`).value));this.shadowRoot.querySelectorAll('[data-override-open]').forEach(b=>b.onclick=()=>{this.deviceId=b.dataset.overrideOpen;this.profileId=this.selectedDevice()?.profile_id||this.profileId;this.view='override';this.page='dashboard';this.syncText();this.render();this.queueCompile()})}
  if(this.page==='providers')q('#providerSave').onclick=async()=>{const type=q('#providerType').value,key=q('#providerKey').value;await this.call('save_provider',{provider_id:q('#providerId').value,provider:{type,url:q('#providerUrl').value,[type==='immich'?'api_key':'token']:key}});await this.refresh()}}
}
customElements.define('rustyhama-panel',RustyHamaPanel);
